### ISSUE TITLE
Login/Registration Encryption

### ISSUE THREAD

**Issue by JimothyGreene** [JimothyGreene/EE461L-Group2-FinalProject#11]
The registration API needs to encrypt the password data before inserting it into the database. The login API needs to then use encryption to validate the password.

**Comment by maxwithrow** [comment]
--Ignore this, forgot about SSL--

Should encryption occur within the frontend prior to sending through the API? Just so that information can't be grabbed in between

**Comment by JimothyGreene** [comment]
That sort of encryption typically happens through HTTPS with a proper SSL certificate. So it's not something we have to handle in our code. I talked to Alex about it and he said he wasn't even sure we have to do that since usually SSL certs cost money.

**Comment by maxwithrow** [comment]
Ahh forgot about SSL, sounds good to me
