### ISSUE TITLE
JWT Token Expiration

### ISSUE THREAD

**Issue by JimothyGreene** [JimothyGreene/EE461L-Group2-FinalProject#48]
Currently, the JWT token expires very quickly. I'm not sure how long exactly, but it expired while I was testing the CRUD operations for hardware sets, which was in the span of less than 10 minutes. We should decide on a good amount of time for expiration and implement that.

**Comment by ishan0102** [comment]
45 mins - 1 hour seems reasonable

**Comment by JimothyGreene** [comment]
I was thinking more along the lines of 1-2 weeks. I'm mainly basing that off of how frequently I have to re sign in to like gmail or GitHub.
